import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Search } from 'lucide-react'
import AdminLayout from '../../components/layout/AdminLayout'
import { getStockAdjustments } from '../../services/stockAdjustmentService'
import { getWarehouses } from '../../services/warehouseService'
import '../brands/brands.css'

export default function StockAdjustmentList() { const [items, setItems] = useState([]); const [warehouses, setWarehouses] = useState([]); const [error, setError] = useState(''); const [filters, setFilters] = useState({ search: '', warehouseId: '', from: '', to: '' }); useEffect(() => { Promise.all([getStockAdjustments(), getWarehouses()]).then(([adjustments, warehouseData]) => { setItems(adjustments); setWarehouses(warehouseData) }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load stock adjustments.')) }, []); const visible = useMemo(() => items.filter((item) => { const date = String(item.adjustmentDate ?? item.date ?? item.createdAt ?? '').slice(0, 10); const text = `${item.id} ${item.reason || ''} ${item.warehouse?.name || item.warehouseName || ''}`.toLowerCase(); return (!filters.search || text.includes(filters.search.toLowerCase())) && (!filters.warehouseId || String(item.warehouseId ?? item.warehouse?.id) === filters.warehouseId) && (!filters.from || date >= filters.from) && (!filters.to || date <= filters.to) }), [items, filters]); const change = (key, value) => setFilters((current) => ({ ...current, [key]: value })); return <AdminLayout title="Stock Adjustments"><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>Stock Adjustments</h2><span>Review inventory corrections and physical-count changes.</span></div><Link className="brand-primary" to="/stock-adjustments/create"><Plus size={17} />Add Adjustment</Link></div><section className="brand-card"><div className="order-filters"><label><Search size={17} /><input value={filters.search} onChange={(event) => change('search', event.target.value)} placeholder="Search adjustments" /></label><label>Warehouse<select value={filters.warehouseId} onChange={(event) => change('warehouseId', event.target.value)}><option value="">All warehouses</option>{warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>From date<input type="date" value={filters.from} onChange={(event) => change('from', event.target.value)} /></label><label>To date<input type="date" min={filters.from} value={filters.to} onChange={(event) => change('to', event.target.value)} /></label></div>{error && <div className="brand-error">{error}</div>}<div className="brand-table"><table><thead><tr><th>ID</th><th>Warehouse</th><th>Adjustment Date</th><th>Reason</th><th>Created</th></tr></thead><tbody>{visible.length ? visible.map((item) => <tr key={item.id}><td>#{item.id}</td><td>{item.warehouse?.name ?? item.warehouseName ?? '—'}</td><td>{item.adjustmentDate ?? item.date ?? '—'}</td><td>{item.reason ?? '—'}</td><td>{item.createdAt ?? '—'}</td></tr>) : <tr><td colSpan="5">No stock adjustments match these filters.</td></tr>}</tbody></table></div></section></div></AdminLayout> }
