import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getWarehouses } from '../../services/warehouseService'
import { getProducts } from '../../services/productService'
import { createStockAdjustment } from '../../services/stockAdjustmentService'
import '../brands/brands.css'

export default function StockAdjustmentForm() {
  const navigate = useNavigate(); const [data, setData] = useState({ warehouses: [], products: [] }); const [form, setForm] = useState({ warehouseId: '', adjustmentDate: new Date().toISOString().slice(0, 10), reason: '', items: [{ productId: '', quantityChange: 0, note: '' }] }); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getWarehouses(), getProducts()]).then(([warehouses, products]) => setData({ warehouses, products })).catch(() => setError('Unable to load warehouses or products.')) }, [])
  const save = async (event) => { event.preventDefault(); try { await createStockAdjustment({ ...form, warehouseId: Number(form.warehouseId), items: form.items.map((item) => ({ ...item, productId: Number(item.productId), quantityChange: Number(item.quantityChange) })) }); navigate('/stock-adjustments') } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save adjustment.') } }
  return <AdminLayout title="Stock Adjustment"><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>Stock Adjustment</h2><span>Correct stock after physical counts or damaged items.</span></div></div><form className="brand-form" onSubmit={save}><section>{error && <div className="brand-error">{error}</div>}<label>Warehouse<select value={form.warehouseId} onChange={(event) => setForm((current) => ({ ...current, warehouseId: event.target.value }))}><option value="">Select warehouse</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Adjustment Date<input type="date" value={form.adjustmentDate} onChange={(event) => setForm((current) => ({ ...current, adjustmentDate: event.target.value }))} /></label><label>Reason<textarea value={form.reason} onChange={(event) => setForm((current) => ({ ...current, reason: event.target.value }))} /></label><h3>Adjustment Items</h3>{form.items.map((item, index) => <div className="three" key={index}><label>Product<select value={item.productId} onChange={(event) => setForm((current) => ({ ...current, items: current.items.map((row, rowIndex) => rowIndex === index ? { ...row, productId: event.target.value } : row) }))}><option value="">Select product</option>{data.products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Quantity Change<input type="number" value={item.quantityChange} onChange={(event) => setForm((current) => ({ ...current, items: current.items.map((row, rowIndex) => rowIndex === index ? { ...row, quantityChange: event.target.value } : row) }))} /></label><label>Item Note<input value={item.note} onChange={(event) => setForm((current) => ({ ...current, items: current.items.map((row, rowIndex) => rowIndex === index ? { ...row, note: event.target.value } : row) }))} /></label></div>)}<button type="button" onClick={() => setForm((current) => ({ ...current, items: [...current.items, { productId: '', quantityChange: 0, note: '' }] }))}>Add item</button><div className="brand-form-actions"><button type="button" onClick={() => navigate(-1)}>Cancel</button><button className="brand-primary">Save Adjustment</button></div></section></form></div></AdminLayout>
}
