import { useEffect, useState } from 'react'
import { Minus, Plus } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getProducts } from '../../services/productService'
import { getWarehouses } from '../../services/warehouseService'
import { createWarehouseRequisition, getWarehouseRequisition, updateWarehouseRequisition } from '../../services/warehouseRequisitionService'
import '../brands/brands.css'

const blankItem = () => ({ productId: '', quantity: 1 })
const blank = { requestingWarehouseId: '', sourceWarehouseId: '', note: '', items: [blankItem()] }
export default function WarehouseRequisitionForm() {
  const navigate = useNavigate(); const { id } = useParams(); const editing = Boolean(id)
  const [data, setData] = useState({ warehouses: [], products: [] }); const [form, setForm] = useState(blank); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { Promise.all([getWarehouses(), getProducts(), editing ? getWarehouseRequisition(id) : Promise.resolve(null)]).then(([warehouses, products, requisition]) => { setData({ warehouses, products }); if (requisition) setForm({ requestingWarehouseId: String(requisition.requestingWarehouseId ?? requisition.requestingWarehouse?.id ?? ''), sourceWarehouseId: String(requisition.sourceWarehouseId ?? requisition.sourceWarehouse?.id ?? ''), note: requisition.note ?? '', items: (requisition.items ?? requisition.requisitionItems ?? [blankItem()]).map((item) => ({ productId: String(item.productId ?? item.product?.id ?? ''), quantity: Number(item.quantity ?? 1) })) }) }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load requisition information.')) }, [editing, id])
  const updateItem = (index, key, value) => setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: key === 'quantity' ? Number(value) : value } : item) }))
  const save = async (event) => { event.preventDefault(); if (!form.requestingWarehouseId || !form.sourceWarehouseId || form.requestingWarehouseId === form.sourceWarehouseId || form.items.some((item) => !item.productId || Number(item.quantity) < 1)) return setError('Choose two different warehouses and complete every item.'); const payload = { requestingWarehouseId: Number(form.requestingWarehouseId), sourceWarehouseId: Number(form.sourceWarehouseId), note: form.note.trim(), items: form.items.map((item) => ({ productId: Number(item.productId), quantity: Number(item.quantity) })) }; try { setSaving(true); setError(''); await (editing ? updateWarehouseRequisition(id, payload) : createWarehouseRequisition(payload)); navigate('/warehouse-requisitions') } catch (requestError) { setError(requestError.response?.data?.message || `Unable to ${editing ? 'update' : 'create'} requisition.`) } finally { setSaving(false) } }
  return <AdminLayout title={editing ? 'Edit Warehouse Requisition' : 'Warehouse Requisition'}><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>{editing ? 'Edit Warehouse Requisition' : 'Warehouse Requisition'}</h2><span>{editing ? 'Update this pending stock request.' : 'Request stock from another warehouse.'}</span></div></div><form className="brand-form" onSubmit={save}><section>{error && <div className="brand-error">{error}</div>}<div className="brand-form-grid"><label>Requesting Warehouse *<select value={form.requestingWarehouseId} onChange={(event) => setForm((current) => ({ ...current, requestingWarehouseId: event.target.value }))}><option value="">Select warehouse</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Source Warehouse *<select value={form.sourceWarehouseId} onChange={(event) => setForm((current) => ({ ...current, sourceWarehouseId: event.target.value }))}><option value="">Select warehouse</option>{data.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label></div><label>Note<textarea value={form.note} onChange={(event) => setForm((current) => ({ ...current, note: event.target.value }))} /></label><div className="order-items-heading"><h3>Items</h3><button type="button" onClick={() => setForm((current) => ({ ...current, items: [...current.items, blankItem()] }))}><Plus size={16} />Add item</button></div>{form.items.map((item, index) => <div className="brand-form-grid order-item-row" key={index}><label>Product *<select value={item.productId} onChange={(event) => updateItem(index, 'productId', event.target.value)}><option value="">Select product</option>{data.products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Quantity *<input type="number" min="1" value={item.quantity} onChange={(event) => updateItem(index, 'quantity', event.target.value)} /></label>{form.items.length > 1 && <button className="order-remove" type="button" onClick={() => setForm((current) => ({ ...current, items: current.items.filter((_, itemIndex) => itemIndex !== index) }))}><Minus size={16} />Remove</button>}</div>)}<div className="brand-form-actions"><button type="button" onClick={() => navigate('/warehouse-requisitions')}>Cancel</button><button className="brand-primary" disabled={saving}>{saving ? 'Saving…' : editing ? 'Update Requisition' : 'Submit Request'}</button></div></section></form></div></AdminLayout>
}
