import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRightLeft, Plus } from 'lucide-react'
import AdminLayout from '../../components/layout/AdminLayout'
import { getWarehouseTransfers } from '../../services/warehouseTransferService'
import '../brands/brands.css'
import '../accounts/accounts-module.css'

const blank = { transfer: '', from: '', to: '', requisition: '', status: '', date: '' }
const includes = (value, filter) => !filter || String(value ?? '').toLowerCase().includes(filter.toLowerCase())
export default function WarehouseTransferList() {
  const [transfers, setTransfers] = useState([]); const [filters, setFilters] = useState(blank); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { setLoading(true); getWarehouseTransfers().then((data) => { setTransfers(data); setError('') }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load warehouse transfers.')).finally(() => setLoading(false)) }, [])
  const shown = useMemo(() => transfers.filter((item) => includes(item.id, filters.transfer) && includes(item.fromWarehouse?.name ?? item.fromWarehouseName, filters.from) && includes(item.toWarehouse?.name ?? item.toWarehouseName, filters.to) && includes(item.requisitionId, filters.requisition) && (!filters.status || String(item.status ?? 'Completed').toLowerCase() === filters.status) && (!filters.date || String(item.createdAt ?? '').slice(0, 10) === filters.date)), [transfers, filters])
  const setFilter = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  return <AdminLayout title="Warehouse Transfers"><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>Warehouse Transfers</h2><span>Track inventory movements between warehouses.</span></div><Link className="brand-primary" to="/warehouse-transfers/create"><Plus size={17} />New Transfer</Link></div><section className="brand-card"><div className="brand-toolbar report-filters individual-filter-grid"><label>Transfer ID<input value={filters.transfer} onChange={(e) => setFilter('transfer', e.target.value)} placeholder="Filter transfer" /></label><label>From warehouse<input value={filters.from} onChange={(e) => setFilter('from', e.target.value)} placeholder="Filter source" /></label><label>To warehouse<input value={filters.to} onChange={(e) => setFilter('to', e.target.value)} placeholder="Filter destination" /></label><label>Requisition ID<input value={filters.requisition} onChange={(e) => setFilter('requisition', e.target.value)} placeholder="Filter requisition" /></label><label>Status<select value={filters.status} onChange={(e) => setFilter('status', e.target.value)}><option value="">All statuses</option><option value="completed">Completed</option><option value="pending">Pending</option><option value="cancelled">Cancelled</option></select></label><label>Date<input type="date" value={filters.date} onChange={(e) => setFilter('date', e.target.value)} /></label><button className="warehouse-clear" type="button" onClick={() => setFilters(blank)}>Clear filters</button></div>{error && <div className="brand-error">{error}</div>}<div className="brand-table"><table><thead><tr><th>Transfer</th><th>From Warehouse</th><th>To Warehouse</th><th>Requisition</th><th>Items</th><th>Status</th><th>Created</th></tr></thead><tbody>{loading ? <tr><td colSpan="7">Loading warehouse transfers…</td></tr> : !shown.length ? <tr><td colSpan="7">No transfers match these filters.</td></tr> : shown.map((transfer, index) => <tr key={transfer.id || index}><td><strong><ArrowRightLeft size={14} /> #{transfer.id || index + 1}</strong></td><td>{transfer.fromWarehouse?.name || transfer.fromWarehouseName || '—'}</td><td>{transfer.toWarehouse?.name || transfer.toWarehouseName || '—'}</td><td>{transfer.requisitionId ? `#${transfer.requisitionId}` : 'Manual'}</td><td>{transfer.items?.length ?? transfer.itemCount ?? '—'}</td><td><span className="brand-status active">{transfer.status || 'Completed'}</span></td><td>{transfer.createdAt ? new Date(transfer.createdAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></div></section></div></AdminLayout>
}
