import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus } from 'lucide-react'
import AdminLayout from '../../components/layout/AdminLayout'
import { getWarehouseRequisitions } from '../../services/warehouseRequisitionService'
import '../brands/brands.css'
import '../accounts/accounts-module.css'

const blank = { request: '', requesting: '', source: '', status: '', from: '', to: '' }
const includes = (value, query) => !query || String(value ?? '').toLowerCase().includes(query.toLowerCase())
export default function WarehouseRequisitionList() {
  const [items, setItems] = useState([]); const [filters, setFilters] = useState(blank); const [error, setError] = useState('')
  useEffect(() => { getWarehouseRequisitions().then(setItems).catch((e) => setError(e.response?.data?.message || 'Unable to load requisitions.')) }, [])
  const shown = useMemo(() => items.filter((item) => { const created = String(item.createdAt ?? '').slice(0, 10); return includes(item.id, filters.request) && includes(item.requestingWarehouse?.name ?? item.requestingWarehouseName, filters.requesting) && includes(item.sourceWarehouse?.name ?? item.sourceWarehouseName, filters.source) && (!filters.status || String(item.status ?? 'pending').toLowerCase() === filters.status) && (!filters.from || created >= filters.from) && (!filters.to || created <= filters.to) }), [items, filters])
  const setFilter = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  return <AdminLayout title="Warehouse Requisitions"><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>Warehouse Requisitions</h2><span>Track stock requests between warehouses.</span></div><Link className="brand-primary" to="/warehouse-requisitions/create"><Plus size={17} />New Requisition</Link></div><section className="brand-card"><div className="brand-toolbar report-filters individual-filter-grid"><label>Request ID<input value={filters.request} onChange={(e) => setFilter('request', e.target.value)} placeholder="Filter request" /></label><label>Requesting warehouse<input value={filters.requesting} onChange={(e) => setFilter('requesting', e.target.value)} placeholder="Filter warehouse" /></label><label>Source warehouse<input value={filters.source} onChange={(e) => setFilter('source', e.target.value)} placeholder="Filter source" /></label><label>Status<select value={filters.status} onChange={(e) => setFilter('status', e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label>From<input type="date" value={filters.from} onChange={(e) => setFilter('from', e.target.value)} /></label><label>To<input type="date" value={filters.to} onChange={(e) => setFilter('to', e.target.value)} /></label><button className="warehouse-clear" type="button" onClick={() => setFilters(blank)}>Clear filters</button></div>{error && <div className="brand-error">{error}</div>}<div className="brand-table"><table><thead><tr><th>Request ID</th><th>Requesting Warehouse</th><th>Source Warehouse</th><th>Note</th><th>Status</th><th>Created</th></tr></thead><tbody>{!shown.length ? <tr><td colSpan="6">No requisitions match these filters.</td></tr> : shown.map((item) => <tr key={item.id}><td>#{item.id}</td><td>{item.requestingWarehouse?.name ?? item.requestingWarehouseName}</td><td>{item.sourceWarehouse?.name ?? item.sourceWarehouseName}</td><td>{item.note || '—'}</td><td>{item.status ?? 'pending'}</td><td>{item.createdAt}</td></tr>)}</tbody></table></div></section></div></AdminLayout>
}
