import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { createBank, getBank, updateBank } from '../../services/bankService'
import '../brands/brands.css'

const blank = { name: '', accountName: '', accountNumber: '', branch: '', routingNumber: '', isActive: true }
export default function BankForm() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id); const [bank, setBank] = useState(blank); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (editing) getBank(id).then((data) => setBank({ ...blank, ...data, isActive: data.isActive ?? true })).catch((e) => setError(e.response?.data?.message || 'Unable to load bank.')) }, [editing, id])
  const change = (event) => { const { name, value, type, checked } = event.target; setBank((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); setError('') }
  const save = async (event) => { event.preventDefault(); if (!bank.name.trim() || !bank.accountName.trim() || !bank.accountNumber.trim()) { setError('Bank name, account name, and account number are required.'); return } setSaving(true); try { await (editing ? updateBank(id, bank) : createBank(bank)); navigate('/banks') } catch (e) { setError(e.response?.data?.message || 'Unable to save bank.') } finally { setSaving(false) } }
  return <AdminLayout title={editing ? 'Edit Bank' : 'Add Bank'}><div className="brand-page"><div className="brand-crumb"><Link to="/dashboard">Dashboard</Link> / <Link to="/banks">Banks</Link> / {editing ? 'Edit Bank' : 'Add Bank'}</div><div className="brand-heading"><div><p>ACCOUNTS</p><h2>{editing ? 'Edit Bank' : 'Add Bank'}</h2><span>Save the official banking details used for financial transactions.</span></div></div><form className="brand-form" onSubmit={save}><section><h3>Bank information</h3>{error && <div className="brand-error">{error}</div>}<label>Bank Name *<input name="name" value={bank.name} onChange={change} placeholder="Dutch Bangla Bank" /></label><label>Account Name *<input name="accountName" value={bank.accountName} onChange={change} placeholder="Ready Ecommerce Ltd." /></label><div className="brand-form-grid"><label>Account Number *<input name="accountNumber" value={bank.accountNumber} onChange={change} placeholder="1234567890" /></label><label>Routing Number<input name="routingNumber" value={bank.routingNumber} onChange={change} placeholder="090261724" /></label></div><label>Branch<input name="branch" value={bank.branch} onChange={change} placeholder="Dhaka Main Branch" /></label><label className="blog-toggle"><input type="checkbox" name="isActive" checked={bank.isActive} onChange={change} /><span><strong>Active bank account</strong><small>Available for financial transactions.</small></span></label><div className="brand-form-actions"><button type="button" onClick={() => navigate('/banks')}>Cancel</button><button className="brand-primary" disabled={saving}>{saving ? 'Saving…' : editing ? 'Update Bank' : 'Save Bank'}</button></div></section><aside><span>BANK PREVIEW</span><div className="brand-preview-logo">{bank.name?.[0] || 'B'}</div><h3>{bank.name || 'Bank name'}</h3><p>{bank.accountName || 'Account name'}</p><p>{bank.accountNumber || 'Account number'}</p><p>{bank.branch || 'Branch'}</p></aside></form></div></AdminLayout>
}
