import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getCustomers } from '../../services/customerService'
import { getEcommerceOrders } from '../../services/ecommerceOrderService'
import { createCustomerPayment } from '../../services/customerPaymentService'
import { getPaymentMethods } from '../../services/paymentMethodService'
import '../brands/brands.css'
import './accounts-module.css'

const blank = { customer_id: '', order_id: '', date: new Date().toISOString().slice(0, 10), remarks: '', amount: '', payment_method_id: '', cheque_number: '' }
const customerName = (customer) => [customer.firstName, customer.lastName].filter(Boolean).join(' ') || customer.name || `Customer #${customer.id}`
const invoiceName = (order) => order.invoiceNumber ?? order.orderNumber ?? order.saleNumber ?? `Invoice #${order.id}`
const dueOf = (order) => Math.max(0, Number(order?.dueAmount ?? order?.due ?? order?.balanceDue ?? ((order?.totalAmount ?? order?.grandTotal ?? order?.total ?? 0) - (order?.paidAmount ?? order?.paid ?? 0))) || 0)
const money = (value) => new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 }).format(Number(value || 0))

export default function CustomerPaymentForm() {
  const navigate = useNavigate(); const [params] = useSearchParams()
  const [form, setForm] = useState(() => ({ ...blank, customer_id: params.get('customerId') || '', order_id: params.get('orderId') || '' }))
  const [options, setOptions] = useState({ customers: [], orders: [], paymentMethods: [] }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { Promise.all([getCustomers(), getEcommerceOrders(), getPaymentMethods()]).then(([customers, orders, paymentMethods]) => setOptions({ customers, orders, paymentMethods })).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load customer invoices.')) }, [])
  const invoices = useMemo(() => options.orders.filter((order) => String(order.customerId ?? order.customer?.id) === String(form.customer_id)), [form.customer_id, options.orders])
  const selectedInvoice = useMemo(() => invoices.find((order) => String(order.id) === String(form.order_id)), [form.order_id, invoices])
  const dueAmount = dueOf(selectedInvoice)
  const change = ({ target: { name, value } }) => { setForm((current) => ({ ...current, [name]: value, ...(name === 'customer_id' ? { order_id: '', amount: '' } : name === 'order_id' ? { amount: '' } : {}) })); setError(''); setSuccess('') }
  const save = async (event) => { event.preventDefault(); const amount = Number(form.amount); if (!form.customer_id || !form.order_id || !form.date || !form.payment_method_id) return setError('Select a customer, invoice, and payment method.'); if (!amount || amount <= 0) return setError('Enter a payment amount greater than zero.'); if (amount > dueAmount) return setError(`Payment cannot exceed the invoice due amount of ${money(dueAmount)}.`); setSaving(true); setError(''); try { await createCustomerPayment(form); setSuccess('Customer payment saved successfully.'); setForm(blank) } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save customer payment.') } finally { setSaving(false) } }
  return <AdminLayout title="Customer Receive"><div className="brand-page"><div className="brand-heading"><div><p>ACCOUNTS</p><h2>Customer Receive</h2><span>Select a customer, then choose an invoice and receive its outstanding payment.</span></div></div><form className="brand-form accounts-entry-form" onSubmit={save}><section><h3>Receipt information</h3>{error && <div className="brand-error">{error}</div>}{success && <div className="brand-success">{success}</div>}<div className="brand-form-grid"><label>Customer *<select name="customer_id" value={form.customer_id} onChange={change}><option value="">Select customer</option>{options.customers.map((customer) => <option key={customer.id} value={customer.id}>{customerName(customer)}</option>)}</select></label><label>Invoice *<select name="order_id" value={form.order_id} onChange={change} disabled={!form.customer_id}><option value="">{form.customer_id ? 'Select customer invoice' : 'Select customer first'}</option>{invoices.map((order) => <option key={order.id} value={order.id}>{invoiceName(order)} — Due {money(dueOf(order))}</option>)}</select></label></div>{selectedInvoice && <div className="payment-due-card"><span>Selected invoice</span><strong>{invoiceName(selectedInvoice)}</strong><b>Due amount: {money(dueAmount)}</b></div>}<div className="brand-form-grid"><label>Payment Date *<input type="date" name="date" value={form.date} onChange={change} /></label><label>Receive Amount *<input type="number" min="0.01" max={dueAmount || undefined} step="0.01" name="amount" value={form.amount} onChange={change} disabled={!selectedInvoice || dueAmount <= 0} placeholder={selectedInvoice ? `Maximum ${dueAmount}` : 'Select invoice first'} /></label></div><label>Payment Method *<select name="payment_method_id" value={form.payment_method_id} onChange={change}><option value="">Select payment method</option>{options.paymentMethods.map((method) => <option key={method.id} value={method.id}>{method.name ?? method.label ?? method.key ?? `Method #${method.id}`}</option>)}</select></label><label>Cheque Number<input name="cheque_number" value={form.cheque_number} onChange={change} placeholder="Only for cheque payment" /></label><label>Remarks<textarea name="remarks" value={form.remarks} onChange={change} rows="4" placeholder="Payment received against invoice" /></label><div className="brand-form-actions"><button type="button" onClick={() => navigate('/chart-of-accounts')}>Cancel</button><button className="brand-primary" disabled={saving || !selectedInvoice || dueAmount <= 0}>{saving ? 'Saving…' : 'Receive Payment'}</button></div></section></form></div></AdminLayout>
}
