import { useEffect, useMemo, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getChartOfAccounts } from '../../services/accountService'
import { createJournalVoucher } from '../../services/journalVoucherService'
import '../brands/brands.css'

const blankEntry = () => ({ account_id: '', debit: '', credit: '' })
const blank = { date: new Date().toISOString().slice(0, 10), ledger_comment: '', sub_type: 'Tax', entries: [blankEntry(), blankEntry()] }
const flattenAccounts = (items) => items.flatMap((item) => [{ id: item.id, name: item.name, code: item.headCode ?? item.code }, ...flattenAccounts(item.children ?? [])])

export default function JournalVoucherForm() {
  const navigate = useNavigate(); const [form, setForm] = useState(blank); const [accounts, setAccounts] = useState([]); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { getChartOfAccounts().then((data) => setAccounts(flattenAccounts(Array.isArray(data) ? data : data?.accounts ?? data?.items ?? []))).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load account heads.')) }, [])
  const totals = useMemo(() => form.entries.reduce((sum, entry) => ({ debit: sum.debit + Number(entry.debit || 0), credit: sum.credit + Number(entry.credit || 0) }), { debit: 0, credit: 0 }), [form.entries])
  const change = ({ target: { name, value } }) => { setForm((current) => ({ ...current, [name]: value })); setError(''); setSuccess('') }
  const changeEntry = (index, name, value) => { setForm((current) => ({ ...current, entries: current.entries.map((entry, entryIndex) => entryIndex === index ? { ...entry, [name]: value, ...(name === 'debit' && value ? { credit: '' } : {}), ...(name === 'credit' && value ? { debit: '' } : {}) } : entry) })); setError(''); setSuccess('') }
  const addEntry = () => setForm((current) => ({ ...current, entries: [...current.entries, blankEntry()] }))
  const removeEntry = (index) => setForm((current) => ({ ...current, entries: current.entries.length > 2 ? current.entries.filter((_, entryIndex) => entryIndex !== index) : current.entries }))
  const save = async (event) => { event.preventDefault(); const validEntries = form.entries.filter((entry) => entry.account_id && (Number(entry.debit) > 0 || Number(entry.credit) > 0)); if (!form.date || !form.ledger_comment || !form.sub_type || validEntries.length < 2) { setError('Add at least two completed journal entries.'); return } if (Math.abs(totals.debit - totals.credit) > 0.001) { setError('Total debit and total credit must be equal.'); return } setSaving(true); setError(''); try { await createJournalVoucher({ ...form, entries: validEntries }); setSuccess('Journal voucher saved successfully.'); setForm(blank) } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save journal voucher.') } finally { setSaving(false) } }
  return <AdminLayout title="Journal Voucher"><div className="brand-page"><div className="brand-heading"><div><p>ACCOUNTS</p><h2>Journal Voucher</h2><span>Record balanced debit and credit accounting entries.</span></div></div><form className="brand-form" onSubmit={save}><section><h3>Voucher information</h3>{error && <div className="brand-error">{error}</div>}{success && <div className="brand-success">{success}</div>}<div className="brand-form-grid"><label>Date *<input type="date" name="date" value={form.date} onChange={change} /></label><label>Sub Type *<input name="sub_type" value={form.sub_type} onChange={change} placeholder="Tax" /></label></div><label>Ledger Comment *<textarea name="ledger_comment" value={form.ledger_comment} onChange={change} rows="3" placeholder="Sales tax adjustment" /></label><div className="journal-heading"><h3>Journal entries</h3><button type="button" className="brand-primary journal-add" onClick={addEntry}><Plus size={16} /> Add Entry</button></div><div className="journal-entries">{form.entries.map((entry, index) => <div className="journal-entry" key={index}><label>Account *<select value={entry.account_id} onChange={(event) => changeEntry(index, 'account_id', event.target.value)}><option value="">{accounts.length ? 'Select account' : 'Loading accounts…'}</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} {account.code ? `(${account.code})` : ''}</option>)}</select></label><label>Debit<input type="number" min="0" step="0.01" value={entry.debit} onChange={(event) => changeEntry(index, 'debit', event.target.value)} placeholder="0.00" /></label><label>Credit<input type="number" min="0" step="0.01" value={entry.credit} onChange={(event) => changeEntry(index, 'credit', event.target.value)} placeholder="0.00" /></label><button type="button" className="journal-remove" onClick={() => removeEntry(index)} disabled={form.entries.length <= 2} aria-label="Remove entry"><Trash2 size={17} /></button></div>)}</div><div className={`journal-total ${Math.abs(totals.debit - totals.credit) < 0.001 && totals.debit > 0 ? 'is-balanced' : ''}`}><span>Total debit: <strong>{totals.debit.toFixed(2)}</strong></span><span>Total credit: <strong>{totals.credit.toFixed(2)}</strong></span><b>{Math.abs(totals.debit - totals.credit) < 0.001 && totals.debit > 0 ? 'Balanced' : 'Not balanced'}</b></div><div className="brand-form-actions"><button type="button" onClick={() => navigate('/chart-of-accounts')}>Cancel</button><button className="brand-primary" disabled={saving}>{saving ? 'Saving…' : 'Save Journal Voucher'}</button></div></section><aside><span>VOUCHER PREVIEW</span><div className="brand-preview-logo">JV</div><h3>{totals.debit.toFixed(2)}</h3><p>{form.sub_type || 'Journal'}</p><p>{form.date}</p><p>{form.ledger_comment || 'Voucher comment'}</p></aside></form></div></AdminLayout>
}
