import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getChartOfAccounts } from '../../services/accountService'
import { getPurchases } from '../../services/purchaseService'
import { getSuppliers } from '../../services/supplierService'
import { createSupplierPayment } from '../../services/supplierPaymentService'
import '../brands/brands.css'

const blank = { supplier_id: '', purchase_id: '', date: new Date().toISOString().slice(0, 10), remarks: '', amount: '', payment_method_id: '', account_id: '', cheque_number: '' }
const children = (item) => item.children ?? []
const flattenAccounts = (items) => items.flatMap((item) => [{ id: item.id, name: item.name, code: item.headCode ?? item.code }, ...flattenAccounts(children(item))])

export default function SupplierPaymentForm() {
  const navigate = useNavigate(); const [form, setForm] = useState(blank); const [options, setOptions] = useState({ suppliers: [], purchases: [], accounts: [] }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { Promise.all([getSuppliers(), getPurchases(), getChartOfAccounts()]).then(([suppliers, purchases, accounts]) => setOptions({ suppliers, purchases, accounts: flattenAccounts(Array.isArray(accounts) ? accounts : accounts?.accounts ?? accounts?.items ?? []) })).catch((e) => setError(e.response?.data?.message || 'Unable to load supplier payment options.')) }, [])
  const supplierPurchases = useMemo(() => options.purchases.filter((purchase) => !form.supplier_id || String(purchase.supplierId ?? purchase.supplier?.id) === String(form.supplier_id)), [form.supplier_id, options.purchases])
  const change = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: value, ...(name === 'supplier_id' ? { purchase_id: '' } : {}) })); setError(''); setSuccess('') }
  const save = async (event) => { event.preventDefault(); if (!form.supplier_id || !form.purchase_id || !form.date || !form.amount || !form.payment_method_id || !form.account_id) { setError('Complete all required payment fields.'); return } setSaving(true); setError(''); try { await createSupplierPayment(form); setSuccess('Supplier payment saved successfully.'); setForm(blank) } catch (e) { setError(e.response?.data?.message || 'Unable to save supplier payment.') } finally { setSaving(false) } }
  return <AdminLayout title="Add Supplier Payment"><div className="brand-page"><div className="brand-heading"><div><p>ACCOUNTS</p><h2>Add Supplier Payment</h2><span>Record a supplier payment against a purchase.</span></div></div><form className="brand-form" onSubmit={save}><section><h3>Payment information</h3>{error && <div className="brand-error">{error}</div>}{success && <div className="brand-success">{success}</div>}<div className="brand-form-grid"><label>Supplier *<select name="supplier_id" value={form.supplier_id} onChange={change}><option value="">Select supplier</option>{options.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label>Purchase *<select name="purchase_id" value={form.purchase_id} onChange={change}><option value="">Select purchase</option>{supplierPurchases.map((purchase) => <option key={purchase.id} value={purchase.id}>{purchase.invoiceNumber || `Purchase #${purchase.id}`}</option>)}</select></label></div><div className="brand-form-grid"><label>Payment Date *<input type="date" name="date" value={form.date} onChange={change} /></label><label>Amount *<input type="number" min="0" step="0.01" name="amount" value={form.amount} onChange={change} placeholder="1000" /></label></div><div className="brand-form-grid"><label>Payment Method ID *<input type="number" min="1" name="payment_method_id" value={form.payment_method_id} onChange={change} placeholder="3" /></label><label>Account *<select name="account_id" value={form.account_id} onChange={change}><option value="">Select account head</option>{options.accounts.map((account) => <option key={account.id} value={account.id}>{account.name} {account.code ? `(${account.code})` : ''}</option>)}</select></label></div><label>Cheque Number<input name="cheque_number" value={form.cheque_number} onChange={change} placeholder="83837878" /></label><label>Remarks<textarea name="remarks" value={form.remarks} onChange={change} rows="4" placeholder="Cheque payment" /></label><div className="brand-form-actions"><button type="button" onClick={() => navigate('/chart-of-accounts')}>Cancel</button><button className="brand-primary" disabled={saving}>{saving ? 'Saving…' : 'Save Supplier Payment'}</button></div></section><aside><span>PAYMENT PREVIEW</span><div className="brand-preview-logo">৳</div><h3>{form.amount || '0.00'}</h3><p>{options.suppliers.find((supplier) => String(supplier.id) === String(form.supplier_id))?.name || 'Supplier name'}</p><p>{form.date}</p><p>{form.remarks || 'Payment remarks'}</p></aside></form></div></AdminLayout>
}
