import { useEffect, useMemo, useState } from 'react'
import { Eye, FileDown, Plus, Search, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import api from '../../services/api'
import '../brands/brands.css'
import './accounts-module.css'

const titles = { debit: 'Debit Vouchers', credit: 'Credit Vouchers', contra: 'Contra Vouchers', journal: 'Journal Vouchers' }
const prefixes = { debit: 'DV', credit: 'CV', contra: 'CTV', journal: 'JV' }
const asList = (data) => Array.isArray(data) ? data : (data?.vouchers ?? data?.items ?? data?.data ?? [])
const text = (value) => value == null ? '—' : typeof value === 'object' ? (value.name ?? value.headName ?? '—') : String(value)
const amount = (row) => Number(row.amount ?? row.totalAmount ?? row.debit ?? row.credit ?? 0).toLocaleString()
const voucherRef = (row, type) => row.voucherNumber ?? row.transactionNo ?? row.referenceNo ?? `${prefixes[type]}-${String(row.id ?? 0).padStart(5, '0')}`
const details = (row, type) => [['Voucher reference', voucherRef(row, type)], ['Database ID', row.id ?? '—'], ['Date', text(row.date ?? row.transactionDate ?? row.createdAt).slice(0, 10)], ['Type', text(row.subType ?? row.sub_type ?? type)], ['Account', text(row.account?.name ?? row.accountName ?? row.account)], ['Reverse account', text(row.reverseAccount?.name ?? row.reverseAccountName ?? row.reverse_account)], ['Amount', amount(row)], ['Comment', text(row.ledgerComment ?? row.ledger_comment ?? row.remarks ?? row.description)]]

export default function VoucherList({ type }) {
  const [rows, setRows] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(null)
  useEffect(() => { setLoading(true); api.get(`/admin/accounts/${type}-vouchers`).then((response) => setRows(asList(response.data?.data ?? response.data))).catch((requestError) => setError(requestError.response?.data?.message || `Unable to load ${titles[type].toLowerCase()}.`)).finally(() => setLoading(false)) }, [type])
  const visible = useMemo(() => rows.filter((row) => Object.values(row).some((value) => text(value).toLowerCase().includes(search.toLowerCase()))).sort((a, b) => Number(a.id ?? 0) - Number(b.id ?? 0)), [rows, search])
  return <AdminLayout title={titles[type]}><div className="brand-page voucher-list"><div className="brand-heading"><div><p>ACCOUNTS</p><h2>{titles[type]}</h2><span>Review saved vouchers and export the displayed list as a PDF.</span></div><div className="voucher-actions"><button type="button" className="voucher-export" onClick={() => window.print()}><FileDown size={16} />Export PDF</button><Link className="brand-primary" to={`/${type}-vouchers/create`}><Plus size={17} />Add Voucher</Link></div></div><section className="brand-card"><div className="brand-toolbar"><label><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search vouchers" /></label></div>{error && <div className="brand-error">{error}</div>}<div className="brand-table"><table><thead><tr><th>SL</th><th>Voucher No.</th><th>Date</th><th>Type</th><th>Account</th><th>Reverse Account</th><th>Amount</th><th>Comment</th><th>Action</th></tr></thead><tbody>{loading ? <tr><td colSpan="9">Loading vouchers…</td></tr> : !visible.length ? <tr><td colSpan="9">No vouchers found.</td></tr> : visible.map((row, index) => <tr key={row.id ?? index}><td>{index + 1}</td><td>{voucherRef(row, type)}</td><td>{text(row.date ?? row.transactionDate ?? row.createdAt).slice(0, 10)}</td><td>{text(row.subType ?? row.sub_type ?? type)}</td><td>{text(row.account?.name ?? row.accountName ?? row.account)}</td><td>{text(row.reverseAccount?.name ?? row.reverseAccountName ?? row.reverse_account)}</td><td><strong>{amount(row)}</strong></td><td>{text(row.ledgerComment ?? row.ledger_comment ?? row.remarks ?? row.description)}</td><td><div className="brand-actions"><button type="button" title="View voucher" onClick={() => setSelected(row)}><Eye size={16} /></button></div></td></tr>)}</tbody></table></div></section></div>{selected && <div className="voucher-modal-backdrop" onMouseDown={() => setSelected(null)}><section className="voucher-modal" onMouseDown={(event) => event.stopPropagation()}><button className="voucher-close" type="button" onClick={() => setSelected(null)} aria-label="Close voucher details"><X size={18} /></button><p>VOUCHER DETAILS</p><h3>{voucherRef(selected, type)}</h3><div>{details(selected, type).map(([label, value]) => <dl key={label}><dt>{label}</dt><dd>{value}</dd></dl>)}</div><button type="button" className="brand-primary" onClick={() => window.print()}><FileDown size={16} />Export PDF</button></section></div>}</AdminLayout>
}
