import { useEffect,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getPurchases } from '../../services/purchaseService'
import { getProducts } from '../../services/productService'
import { createPurchaseReturn } from '../../services/purchaseReturnService'
import '../brands/brands.css'
const blank={purchaseId:'',returnDate:new Date().toISOString().slice(0,10),reason:'',items:[{productId:'',quantity:1}]}
export default function PurchaseReturnForm(){const nav=useNavigate(),[form,setForm]=useState(blank),[data,setData]=useState({purchases:[],products:[]}),[error,setError]=useState('');useEffect(()=>{Promise.all([getPurchases(),getProducts()]).then(([purchases,products])=>setData({purchases,products})).catch(()=>setError('Unable to load purchases or products.'))},[]);const item=(i,k,v)=>setForm(x=>({...x,items:x.items.map((r,n)=>n===i?{...r,[k]:k==='quantity'?Number(v):v}:r)}));const save=async e=>{e.preventDefault();if(!form.purchaseId||form.items.some(x=>!x.productId))return setError('Select the original purchase and returned products.');try{await createPurchaseReturn({...form,purchaseId:Number(form.purchaseId),items:form.items.map(x=>({...x,productId:Number(x.productId)}))});nav('/purchases')}catch(err){setError(err.response?.data?.message||'Unable to create purchase return.')}};return <AdminLayout title="Add Purchase Return"><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>Add Purchase Return</h2><span>Record products returned to a supplier.</span></div></div><form className="brand-form" onSubmit={save}><section><h3>Return information</h3>{error&&<div className="brand-error">{error}</div>}<label>Purchase<select value={form.purchaseId} onChange={e=>setForm(x=>({...x,purchaseId:e.target.value}))}><option value="">Select Purchase</option>{data.purchases.map(x=><option key={x.id} value={x.id}>{x.invoiceNumber||`Purchase #${x.id}`}</option>)}</select></label><label>Return Date<input type="date" value={form.returnDate} onChange={e=>setForm(x=>({...x,returnDate:e.target.value}))}/></label><label>Reason<textarea value={form.reason} onChange={e=>setForm(x=>({...x,reason:e.target.value}))}/></label><h3>Returned Items</h3>{form.items.map((r,i)=><div className="two" key={i}><label>Product<select value={r.productId} onChange={e=>item(i,'productId',e.target.value)}><option value="">Select Product</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input type="number" min="1" value={r.quantity} onChange={e=>item(i,'quantity',e.target.value)}/></label></div>)}<button type="button" onClick={()=>setForm(x=>({...x,items:[...x.items,{productId:'',quantity:1}]}))}>Add item</button><div className="brand-form-actions"><button type="button" onClick={()=>nav(-1)}>Cancel</button><button className="brand-primary">Save Return</button></div></section></form></div></AdminLayout>}
