import { useEffect, useState } from 'react'
import { ArrowLeft, Link2, Menu, PanelTop } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getCmsPages } from '../../services/cmsPageService'
import { createCmsMenu, getCmsMenu, getCmsMenus, updateCmsMenu } from '../../services/cmsMenuService'
import './cms.css'
import './cmsMenus.css'

const initial = { location: 'header', label: '', url: '', pageId: '', parentId: '', sortOrder: 0, openInNewTab: false, isActive: true }

export default function CmsMenuForm() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id)
  const [form, setForm] = useState(initial); const [pages, setPages] = useState([]); const [menus, setMenus] = useState([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { Promise.all([getCmsPages(), getCmsMenus(), editing ? getCmsMenu(id) : Promise.resolve(null)]).then(([cmsPages, menuItems, item]) => { setPages(cmsPages); setMenus(menuItems); if (item) setForm({ location: item.location, label: item.label, url: item.url, pageId: item.pageId ?? '', parentId: item.parentId ?? '', sortOrder: item.sortOrder, openInNewTab: item.openInNewTab, isActive: Boolean(item.isActive) }) }).catch((err) => setError(err.response?.data?.message || 'Unable to load menu details.')) }, [editing, id])
  const change = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })); setError('') }
  const choosePage = (event) => { const pageId = event.target.value; const page = pages.find((item) => String(item.id) === pageId); setForm((current) => ({ ...current, pageId, url: page ? `/pages/${page.slug}` : current.url, label: page && !current.label ? page.title : current.label })) }
  const submit = async (event) => { event.preventDefault(); if (!form.label.trim() || !form.url.trim()) return setError('Menu label and URL are required.'); const payload = { location: form.location, label: form.label.trim(), url: form.url.trim(), pageId: form.pageId ? Number(form.pageId) : null, parentId: form.parentId ? Number(form.parentId) : null, sortOrder: Number(form.sortOrder) || 0, openInNewTab: form.openInNewTab, isActive: form.isActive }; setSaving(true); try { await (editing ? updateCmsMenu(id, payload) : createCmsMenu(payload)); navigate('/cms-menus') } catch (err) { setError(err.response?.data?.message || 'Unable to save this menu item.') } finally { setSaving(false) } }
  const parentOptions = menus.filter((item) => String(item.id) !== String(id) && item.location === form.location)
  return <AdminLayout title={editing ? 'Edit CMS Menu' : 'Add CMS Menu'}><div className="cms-page"><div className="cms-crumb"><Link to="/cms-menus"><ArrowLeft size={14} /> CMS Menus</Link> / {editing ? 'Edit Menu Item' : 'Add Menu Item'}</div><div className="cms-heading"><div><p>MARKETING & CONTENT</p><h2>{editing ? 'Edit CMS Menu Item' : 'Add CMS Menu Item'}</h2><span>Add links to the storefront header or footer.</span></div></div><form className="cms-form cms-menu-form" onSubmit={submit}><section>{error && <div className="cms-error">{error}</div>}<h3><Menu size={18} /> Menu item details</h3><div className="cms-fields"><label>Location *<select name="location" value={form.location} onChange={change}><option value="header">Header</option><option value="footer">Footer</option></select></label><label>Sort Order *<input type="number" min="0" name="sortOrder" value={form.sortOrder} onChange={change} /></label></div><label>Menu Label *<input name="label" value={form.label} onChange={change} placeholder="About Us" /></label><label>Link to CMS Page <select value={form.pageId} onChange={choosePage}><option value="">Custom URL (no CMS page)</option>{pages.map((page) => <option key={page.id} value={page.id}>{page.title}</option>)}</select><small className="cms-help">Selecting a CMS page automatically fills its URL.</small></label><label>URL *<div className="slug-input"><Link2 size={15} /><input name="url" value={form.url} onChange={change} placeholder="/pages/about-us" /></div></label><label>Parent Menu Item <select name="parentId" value={form.parentId} onChange={change}><option value="">No parent (top-level link)</option>{parentOptions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className="cms-toggles"><label className="cms-toggle"><input type="checkbox" name="openInNewTab" checked={form.openInNewTab} onChange={change} /><span><strong>Open in new tab</strong><small>Open the link in a separate browser tab.</small></span></label><label className="cms-toggle"><input type="checkbox" name="isActive" checked={form.isActive} onChange={change} /><span><strong>Active menu item</strong><small>Display this item in the selected menu.</small></span></label></div><div className="cms-form-actions"><button type="button" onClick={() => navigate('/cms-menus')}>Cancel</button><button className="cms-primary" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save Changes' : 'Create Menu Item'}</button></div></section><aside><span>MENU PREVIEW</span><div className="cms-menu-preview"><div><PanelTop size={17} /><strong>{form.location === 'header' ? 'Store Header' : 'Store Footer'}</strong></div><p>Home <b>{form.label || 'Menu label'}</b> Shop Contact</p></div><p>{form.isActive ? 'Visible to customers' : 'Hidden from customers'}</p></aside></form></div></AdminLayout>
}
