import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Code2, FileText, Globe2 } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { createCmsPage, getCmsPage, updateCmsPage } from '../../services/cmsPageService'
import './cms.css'

const initialForm = { title: '', slug: '', content: '', seoTitle: '', seoDescription: '', isActive: true }
const slugify = (value) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

export default function CmsPageForm() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id)
  const [form, setForm] = useState(initialForm); const [slugEdited, setSlugEdited] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (!editing) return; getCmsPage(id).then((page) => { setForm({ title: page.title, slug: page.slug, content: page.content, seoTitle: page.seoTitle || '', seoDescription: page.seoDescription || '', isActive: Boolean(page.isActive) }); setSlugEdited(true) }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load this CMS page.')) }, [editing, id])
  const change = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value, ...(name === 'title' && !slugEdited ? { slug: slugify(value) } : {}) })); if (name === 'slug') setSlugEdited(true); setError('') }
  const submit = async (event) => { event.preventDefault(); if (!form.title.trim() || !form.slug.trim() || !form.content.trim()) return setError('Title, slug, and page content are required.'); setSaving(true); try { const payload = { title: form.title.trim(), slug: slugify(form.slug), content: form.content, seoTitle: form.seoTitle.trim(), seoDescription: form.seoDescription.trim(), isActive: form.isActive }; await (editing ? updateCmsPage(id, payload) : createCmsPage(payload)); navigate('/cms-pages') } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save CMS page.') } finally { setSaving(false) } }
  const preview = useMemo(() => ({ __html: form.content || '<p>Your page content will appear here.</p>' }), [form.content])
  return <AdminLayout title={editing ? 'Edit CMS Page' : 'Add CMS Page'}><div className="cms-page"><div className="cms-crumb"><Link to="/cms-pages"><ArrowLeft size={14} /> CMS Pages</Link> / {editing ? 'Edit Page' : 'Add Page'}</div><div className="cms-heading"><div><p>MARKETING & CONTENT</p><h2>{editing ? 'Edit CMS Page' : 'Add CMS Page'}</h2><span>Create a customer-facing policy, support, or information page.</span></div></div><form className="cms-form" onSubmit={submit}><section>{error && <div className="cms-error">{error}</div>}<h3><FileText size={18} /> Page information</h3><div className="cms-fields"><label>Page Title *<input name="title" value={form.title} onChange={change} placeholder="Privacy Policy" /></label><label>URL Slug *<div className="slug-input"><span>/</span><input name="slug" value={form.slug} onChange={change} placeholder="privacy-policy" /></div></label></div><label>Page Content *<span className="editor-label"><Code2 size={14} /> HTML is supported</span><textarea name="content" value={form.content} onChange={change} rows="16" placeholder={'<h1>Privacy Policy</h1>\n<p>Write your page content here...</p>'} /></label><h3><Globe2 size={18} /> SEO settings</h3><div className="cms-fields"><label>SEO Title<input name="seoTitle" value={form.seoTitle} onChange={change} placeholder="About Us | Your Store" /></label><label>SEO Description<textarea name="seoDescription" value={form.seoDescription} onChange={change} rows="3" placeholder="A short description shown in search results." /></label></div><label className="cms-toggle"><input type="checkbox" name="isActive" checked={form.isActive} onChange={change} /><span><strong>Publish this page</strong><small>Visible to customers at /cms/pages/{form.slug || 'your-page'}</small></span></label><div className="cms-form-actions"><button type="button" onClick={() => navigate('/cms-pages')}>Cancel</button><button className="cms-primary" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save Changes' : 'Create Page'}</button></div></section><aside><span>LIVE PREVIEW</span><div className="cms-preview-url"><Globe2 size={14} /> your-store.com/cms/pages/{form.slug || 'your-page'}</div><article dangerouslySetInnerHTML={preview} /></aside></form></div></AdminLayout>
}
