import { useEffect, useState } from 'react'
import { ArrowLeft, Printer } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getPosSale } from '../../services/posSaleService'
import '../brands/brands.css'

const money = (value) => `৳${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
export default function PosSaleInvoice() { const { id } = useParams(); const navigate = useNavigate(); const [sale, setSale] = useState(null); const [error, setError] = useState(''); useEffect(() => { getPosSale(id).then(setSale).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load POS invoice.')) }, [id]); const items = sale?.items || sale?.saleItems || []; const customer = sale?.customer || {}; return <AdminLayout title="POS Invoice"><div className="brand-page order-invoice-page"><button className="brand-back" onClick={() => navigate('/pos-sales')}><ArrowLeft size={16} />Back to POS Sales</button>{error && <div className="brand-error">{error}</div>}{!sale ? !error && <div className="brand-card">Loading invoice…</div> : <><div className="brand-heading"><div><p>POINT OF SALE</p><h2>POS Sale Invoice</h2><span>#{sale.invoiceNumber || sale.id}</span></div><button className="brand-primary" onClick={() => window.print()}><Printer size={16} />Print Invoice</button></div><section className="order-invoice"><header><div><span>POS SALE INVOICE</span><h3>#{sale.invoiceNumber || sale.id}</h3><p>{new Date(sale.saleDate || sale.createdAt).toLocaleString()}</p></div><b>Paid</b></header><div className="order-invoice-parties"><div><span>CUSTOMER</span><strong>{[customer.firstName, customer.lastName].filter(Boolean).join(' ') || customer.name || sale.customerName || '—'}</strong><p>{customer.phone || sale.customerPhone || ''}</p></div><div><span>WAREHOUSE</span><strong>{sale.warehouse?.name || sale.warehouseName || '—'}</strong></div><div><span>PAYMENT</span><strong>{sale.paymentMethod || 'cash'}</strong><p>Paid in full</p></div></div><div className="brand-table"><table><thead><tr><th>Product</th><th>Quantity</th><th>Price</th><th>Discount</th><th>Total</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.id || index}><td>{item.product?.name || item.productName || `Product #${item.productId}`}</td><td>{item.quantity}</td><td>{money(item.price ?? item.unitPrice)}</td><td>{money(item.discount)}</td><td><strong>{money(item.lineTotal ?? ((item.price ?? item.unitPrice) * item.quantity - (item.discount || 0)))}</strong></td></tr>)}</tbody></table></div><div className="order-invoice-bottom"><div><span>Note</span><p>{sale.note || '—'}</p></div><div className="order-invoice-totals"><p><span>Grand total</span><b>{money(sale.grandTotal ?? sale.totalAmount ?? sale.total)}</b></p><p className="invoice-grand"><span>Paid amount</span><b>{money(sale.paidAmount ?? sale.grandTotal ?? sale.totalAmount)}</b></p></div></div></section></>}</div></AdminLayout> }
