import { useEffect, useMemo, useState } from 'react'
import { FileText, Plus, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import AdminLayout from '../../components/layout/AdminLayout'
import { getCustomers } from '../../services/customerService'
import { getPosSales } from '../../services/posSaleService'
import { getWarehouses } from '../../services/warehouseService'
import '../brands/brands.css'

const customerName = (customer) => [customer?.firstName, customer?.lastName].filter(Boolean).join(' ') || customer?.name || ''
const dateValue = (sale) => String(sale.saleDate ?? sale.createdAt ?? sale.created_at ?? '').slice(0, 10)

export default function PosSaleList() {
  const [sales, setSales] = useState([]); const [options, setOptions] = useState({ warehouses: [], customers: [] }); const [error, setError] = useState(''); const [filters, setFilters] = useState({ search: '', warehouseId: '', customerId: '', from: '', to: '' })
  useEffect(() => { Promise.all([getPosSales(), getWarehouses(), getCustomers()]).then(([salesData, warehouses, customers]) => { setSales(salesData); setOptions({ warehouses, customers }) }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load POS sales.')) }, [])
  const visible = useMemo(() => sales.filter((sale) => { const text = `${sale.id} ${sale.invoiceNumber ?? ''} ${customerName(sale.customer) || sale.customerName || ''}`.toLowerCase(); const date = dateValue(sale); return (!filters.search || text.includes(filters.search.toLowerCase())) && (!filters.warehouseId || String(sale.warehouseId ?? sale.warehouse?.id) === filters.warehouseId) && (!filters.customerId || String(sale.customerId ?? sale.customer?.id) === filters.customerId) && (!filters.from || date >= filters.from) && (!filters.to || date <= filters.to) }), [sales, filters])
  const change = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  return <AdminLayout title="POS Sales History"><div className="brand-page"><div className="brand-heading"><div><p>POINT OF SALE</p><h2>POS Sales History</h2><span>Review completed counter sales.</span></div><Link className="brand-primary" to="/pos-sales/create"><Plus size={17} />New POS Sale</Link></div><section className="brand-card"><div className="order-filters"><label><Search size={17} /><input value={filters.search} onChange={(event) => change('search', event.target.value)} placeholder="Search sale or customer" /></label><label>Warehouse<select value={filters.warehouseId} onChange={(event) => change('warehouseId', event.target.value)}><option value="">All warehouses</option>{options.warehouses.map((warehouse) => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></label><label>Customer<select value={filters.customerId} onChange={(event) => change('customerId', event.target.value)}><option value="">All customers</option>{options.customers.map((customer) => <option key={customer.id} value={customer.id}>{customerName(customer)}</option>)}</select></label><label>From date<input type="date" value={filters.from} onChange={(event) => change('from', event.target.value)} /></label><label>To date<input type="date" min={filters.from} value={filters.to} onChange={(event) => change('to', event.target.value)} /></label></div>{error && <div className="brand-error">{error}</div>}<div className="brand-table"><table><thead><tr><th>Sale ID</th><th>Customer</th><th>Warehouse</th><th>Payment</th><th>Total</th><th>Paid</th><th>Date</th><th>Invoice</th></tr></thead><tbody>{visible.length ? visible.map((sale) => <tr key={sale.id}><td>#{sale.invoiceNumber || sale.id}</td><td>{customerName(sale.customer) || sale.customerName || '—'}</td><td>{sale.warehouse?.name || sale.warehouseName || '—'}</td><td>{sale.paymentMethod || 'cash'}</td><td>{sale.totalAmount ?? sale.grandTotal ?? sale.total ?? 0}</td><td>{sale.paidAmount ?? 0}</td><td>{dateValue(sale) || '—'}</td><td><Link className="table-icon-link" to={`/pos-sales/${sale.id}/invoice`} title="View invoice"><FileText size={16} /></Link></td></tr>) : <tr><td colSpan="8">No POS sales match these filters.</td></tr>}</tbody></table></div></section></div></AdminLayout>
}
