import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import AdminLayout from '../../components/layout/AdminLayout'
import { deleteSupplier, getSuppliers } from '../../services/supplierService'
import '../brands/brands.css'
import './suppliers.css'

export default function SupplierList() {
  const [items, setItems] = useState([]); const [filters, setFilters] = useState({ name: '', phone: '', email: '', address: '', status: '' }); const [error, setError] = useState('')
  const load = () => getSuppliers().then(setItems).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load suppliers.'))
  useEffect(() => { load() }, [])
  const visibleItems = useMemo(() => items.filter((supplier) => (!filters.name || String(supplier.name || '').toLowerCase().includes(filters.name.toLowerCase())) && (!filters.phone || String(supplier.phone || '').includes(filters.phone)) && (!filters.email || String(supplier.email || '').toLowerCase().includes(filters.email.toLowerCase())) && (!filters.address || String(supplier.address || '').toLowerCase().includes(filters.address.toLowerCase())) && (!filters.status || String(Boolean(supplier.isActive)) === filters.status)), [items, filters])
  const change = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  return <AdminLayout title="Suppliers"><div className="brand-page"><div className="brand-heading"><div><p>INVENTORY & PURCHASE</p><h2>Suppliers</h2><span>Manage supplier contacts for purchasing and inventory.</span></div><Link className="brand-primary" to="/suppliers/create"><Plus size={17} />Add Supplier</Link></div><section className="brand-card"><div className="order-filters"><label>Supplier name<input value={filters.name} onChange={(event) => change('name', event.target.value)} placeholder="Filter by name" /></label><label>Phone<input value={filters.phone} onChange={(event) => change('phone', event.target.value)} placeholder="Filter by phone" /></label><label>Email<input value={filters.email} onChange={(event) => change('email', event.target.value)} placeholder="Filter by email" /></label><label>Address<input value={filters.address} onChange={(event) => change('address', event.target.value)} placeholder="Filter by address" /></label><label>Status<select value={filters.status} onChange={(event) => change('status', event.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label></div>{error && <div className="brand-error">{error}</div>}<div className="brand-table"><table><thead><tr><th>Supplier</th><th>Phone</th><th>Email</th><th>Address</th><th>Status</th><th>Action</th></tr></thead><tbody>{visibleItems.map((supplier) => <tr key={supplier.id}><td><strong>{supplier.name}</strong></td><td>{supplier.phone}</td><td>{supplier.email}</td><td>{supplier.address}</td><td><span className={`brand-status ${supplier.isActive ? 'active' : 'inactive'}`}>{supplier.isActive ? 'active' : 'inactive'}</span></td><td><div className="brand-actions"><Link to={`/suppliers/${supplier.id}/edit`}><Pencil size={16} /></Link><button type="button" onClick={async () => { if (confirm('Delete this supplier?')) { await deleteSupplier(supplier.id); load() } }}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>{!error && visibleItems.length === 0 && <div className="brand-empty">No suppliers match these filters.</div>}</section></div></AdminLayout>
}
